# Generated by Django 2.0.9 on 2023-11-15 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='complaints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctitle', models.CharField(max_length=100)),
                ('cdescription', models.CharField(max_length=500)),
                ('cdate', models.CharField(max_length=20)),
                ('creply', models.CharField(max_length=500)),
                ('rdate', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.CharField(max_length=200)),
                ('eventdate', models.CharField(max_length=100)),
                ('eventphoto', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=20)),
                ('usertype', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('type', models.CharField(max_length=200)),
                ('mark', models.IntegerField()),
                ('grade', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('discription', models.CharField(max_length=500)),
                ('date', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='pallocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentname', models.CharField(max_length=100)),
                ('phoneno', models.BigIntegerField()),
                ('emailid', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='sallocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffname', models.CharField(max_length=200)),
                ('photo', models.CharField(max_length=200)),
                ('qualification', models.CharField(max_length=400)),
                ('number', models.BigIntegerField()),
                ('email', models.CharField(max_length=100)),
                ('staffexperiance', models.CharField(max_length=500)),
                ('post', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='departmentmanagement.login')),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(max_length=200)),
                ('year', models.BigIntegerField()),
                ('semester', models.IntegerField()),
                ('dateofbirth', models.BigIntegerField()),
                ('admissionno', models.BigIntegerField()),
                ('registerno', models.BigIntegerField()),
                ('phoneno', models.BigIntegerField()),
                ('photo', models.CharField(max_length=100)),
                ('emailid', models.CharField(max_length=100)),
                ('housename', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('postoffice', models.CharField(max_length=100)),
                ('pincode', models.BigIntegerField()),
                ('guardianname', models.CharField(max_length=100)),
                ('phonenumber', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectname', models.CharField(max_length=100)),
                ('subjectcode', models.CharField(max_length=100)),
                ('subjectsyllubus', models.CharField(max_length=200)),
                ('semester', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=100)),
                ('hour', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='sallocation',
            name='STAFF',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='departmentmanagement.staff'),
        ),
        migrations.AddField(
            model_name='sallocation',
            name='SUBJECT',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='departmentmanagement.subject'),
        ),
        migrations.AddField(
            model_name='pallocation',
            name='PARENT',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='departmentmanagement.parent'),
        ),
        migrations.AddField(
            model_name='pallocation',
            name='STUDENT',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='departmentmanagement.student'),
        ),
        migrations.AddField(
            model_name='mark',
            name='SALLOCATION',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='departmentmanagement.sallocation'),
        ),
        migrations.AddField(
            model_name='mark',
            name='STUDENT',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='departmentmanagement.student'),
        ),
        migrations.AddField(
            model_name='mark',
            name='SUBJECT',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='departmentmanagement.subject'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='SALLOCATION',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='departmentmanagement.sallocation'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='STUDENT',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='departmentmanagement.student'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='SUBJECT',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='departmentmanagement.subject'),
        ),
    ]
