# Generated by Django 2.0.9 on 2023-11-16 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departmentmanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rp', models.CharField(max_length=500)),
                ('rd', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='complaints',
        ),
        migrations.AlterField(
            model_name='student',
            name='registerno',
            field=models.CharField(max_length=100),
        ),
    ]
