# Generated by Django 2.0.9 on 2023-11-16 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departmentmanagement', '0002_auto_20231116_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='complaints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctitle', models.CharField(max_length=100)),
                ('cdescription', models.CharField(max_length=500)),
                ('cdate', models.CharField(max_length=20)),
                ('creply', models.CharField(max_length=500)),
                ('rdate', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='reply',
        ),
    ]
