# Generated by Django 3.2.14 on 2024-01-31 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departmentmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.CharField(default=1, max_length=200),
        ),
    ]
