# Generated by Django 2.0.9 on 2024-02-15 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departmentmanagement', '0002_attendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gen',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
