# Generated by Django 2.0.9 on 2024-02-15 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departmentmanagement', '0003_student_gen'),
    ]

    operations = [
        migrations.AddField(
            model_name='sallocation',
            name='year',
            field=models.BigIntegerField(default=1),
        ),
    ]
