# Generated by Django 2.0.9 on 2024-02-15 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departmentmanagement', '0004_sallocation_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sallocation',
            name='year',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.CharField(max_length=50),
        ),
    ]
