# Generated by Django 2.0.9 on 2024-02-15 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departmentmanagement', '0005_auto_20240215_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='tutorallo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=50)),
                ('STAFF', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='departmentmanagement.staff')),
            ],
        ),
    ]
