# Generated by Django 2.0.9 on 2024-02-15 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departmentmanagement', '0006_tutorallo'),
    ]

    operations = [
        migrations.CreateModel(
            name='externalmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(default=1, max_length=100)),
                ('file', models.CharField(max_length=200)),
                ('STUDENT', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='departmentmanagement.student')),
            ],
        ),
    ]
