# Generated by Django 2.0.9 on 2024-02-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departmentmanagement', '0007_externalmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalmark',
            name='type',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
