# Generated by Django 2.0.9 on 2024-02-15 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departmentmanagement', '0008_externalmark_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='additionalinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadharno', models.CharField(max_length=20)),
                ('bloodg', models.CharField(max_length=20)),
                ('height', models.CharField(max_length=20)),
                ('weight', models.CharField(max_length=20)),
                ('religion', models.CharField(max_length=20)),
                ('caste', models.CharField(max_length=20)),
                ('annincome', models.CharField(max_length=20)),
                ('rationcard', models.CharField(max_length=20)),
                ('skills', models.CharField(max_length=500)),
                ('ten', models.CharField(max_length=20)),
                ('plustwo', models.CharField(max_length=20)),
                ('languages', models.CharField(max_length=50)),
                ('STUDENT', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='departmentmanagement.student')),
            ],
        ),
        migrations.AddField(
            model_name='parent',
            name='occupation',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
